@startuml architecture

!include <awslib/AWSCommon>
!include <awslib/AWSSimplified.puml>
!include <awslib/Analytics/ManagedStreamingforKafka.puml>

package "VPC" {
  ManagedStreamingforKafka(msk, "MSK Cluster", " ")
}

@enduml